### ISSUE TITLE
Refactor classes to class directive

### ISSUE THREAD

**Issue by therealcoder1337** [quaffui/quaff#42]
Currently we're calculating all classes at once using a helper function. While this offers a great dev experience, it might not be the best in terms of performance. Hence we should refactor our classes to use the class directive `class:myclass={myclass}` and the shorthand `class:myclass` where possible.

**Comment by therealcoder1337** [comment]
@KilDesu Since you've worked on this, I'm closing here. :)

**Comment by KilDesu** [comment]
#46

**Comment by KilDesu** [comment]
46

**Comment by KilDesu** [comment]
#46
