### ISSUE TITLE
Unwanted `docs.snippet.ts` automatically generated

### ISSUE THREAD

**Issue by KilDesu** [quaffui/quaff#71]
It's been already multiple times that a file `docs.snippet.ts` is automatically generated at 3 different places:
- `lib/src/routes`
- `lib/src/routes/dev`
- `lib/src/routes/layout`

We have to find where this problem come from and fix it.

**Comment by therealcoder1337** [comment]
@KilDesu Could you please check if this still persists after #89?

**Comment by KilDesu** [comment]
Well, no reproduction since then so I guess we could close this issue
